"""empty message

Revision ID: 38c5bc6b4526
Revises: fd12f9000d93
Create Date: 2019-09-26 21:15:01.636249

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38c5bc6b4526'
down_revision = 'fd12f9000d93'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('marks', sa.Column('parameter6', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('marks', 'parameter6')
    # ### end Alembic commands ###
