"""empty message

Revision ID: 75fdc2df990e
Revises: 38c5bc6b4526
Create Date: 2019-09-26 21:15:56.681485

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75fdc2df990e'
down_revision = '38c5bc6b4526'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('marks', 'parameter3')
    op.drop_column('marks', 'parameter6')
    op.drop_column('marks', 'parameter2')
    op.drop_column('marks', 'parameter4')
    op.drop_column('marks', 'parameter5')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('marks', sa.Column('parameter5', sa.INTEGER(), nullable=False))
    op.add_column('marks', sa.Column('parameter4', sa.INTEGER(), nullable=False))
    op.add_column('marks', sa.Column('parameter2', sa.INTEGER(), nullable=False))
    op.add_column('marks', sa.Column('parameter6', sa.INTEGER(), nullable=True))
    op.add_column('marks', sa.Column('parameter3', sa.INTEGER(), nullable=False))
    # ### end Alembic commands ###
