"""empty message

Revision ID: fd12f9000d93
Revises: 
Create Date: 2019-08-26 14:47:24.065768

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd12f9000d93'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('grades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('aPlus', sa.Integer(), nullable=False),
    sa.Column('a', sa.Integer(), nullable=False),
    sa.Column('bPlus', sa.Integer(), nullable=False),
    sa.Column('b', sa.Integer(), nullable=False),
    sa.Column('cPlus', sa.Integer(), nullable=False),
    sa.Column('c', sa.Integer(), nullable=False),
    sa.Column('dPlus', sa.Integer(), nullable=False),
    sa.Column('d', sa.Integer(), nullable=False),
    sa.Column('f', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('guide',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('username', sa.String(length=8), nullable=False),
    sa.Column('password', sa.String(length=8), nullable=False),
    sa.Column('interest', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('marks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parameter1', sa.Integer(), nullable=False),
    sa.Column('parameter2', sa.Integer(), nullable=False),
    sa.Column('parameter3', sa.Integer(), nullable=False),
    sa.Column('parameter4', sa.Integer(), nullable=False),
    sa.Column('parameter5', sa.Integer(), nullable=False),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('team',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('demo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('demo_date', sa.DateTime(), nullable=False),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('marks_id', sa.Integer(), nullable=True),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['marks_id'], ['marks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=50), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=True),
    sa.Column('desc', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('guide_id', sa.Integer(), nullable=True),
    sa.Column('external_id', sa.Integer(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('techUsed', sa.Text(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['external_id'], ['guide.id'], ),
    sa.ForeignKeyConstraint(['guide_id'], ['guide.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    op.create_table('student',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=10), nullable=False),
    sa.Column('cls', sa.String(length=7), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project_guide_demo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('guide_id', sa.Integer(), nullable=True),
    sa.Column('demo_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['demo_id'], ['demo.id'], ),
    sa.ForeignKeyConstraint(['guide_id'], ['guide.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('project_guide_demo')
    op.drop_table('student')
    op.drop_table('project')
    op.drop_table('demo')
    op.drop_table('team')
    op.drop_table('marks')
    op.drop_table('guide')
    op.drop_table('grades')
    # ### end Alembic commands ###
